name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [x86, x64]
        variants: [debug, release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: |
        pip install clang-format
        git config --global user.email "action@github.com"
        git config --global user.name "action"

    - name: Refactor
      run: |
        clang-format -i -style=file:.clang-format *.c
        git add .
        git commit -m "Refactor by Github Actions"
        git push origin main

    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: ${{ matrix.arch }}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake --preset ${{ matrix.arch }}-${{ matrix.variants }}
        cmake --build out/build/${{ matrix.arch }}-${{ matrix.variants }}
        cmake --install out/build/${{ matrix.arch }}-${{ matrix.variants }}
