name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: write

jobs:
  refactor_and_analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Set target branch (PR)
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "TARGET_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV

    - name: Set target branch (push)
      if: ${{ github.event_name == 'push' }}
      run: echo "TARGET_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Through undefined branch error
      if: ${{ env.TARGET_BRANCH == null}}
      run: echo "TARGET_BRANCH is undefined" 1>&2 && expr 0 > /dev/null
      
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.TARGET_BRANCH }}

    - name: Set changed files
      id: changes
      run: |
        git fetch origin main --depth 1
        echo "FILES_CHANGED=`\
          (git diff --name-only --diff-filter=AM origin/main..HEAD 2> /dev/null) \
          | grep -E "^.*\.(c|h|cpp|hpp)"           \
          | sed -z "s/\n/ /g"                      \
        `" >> $GITHUB_OUTPUT

    - name: Setup python
      if: ${{ steps.changes.outputs.FILES_CHANGED != null }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install tools
      if: ${{ steps.changes.outputs.FILES_CHANGED != null }}
      run: |
        sudo apt install clang-format
        pip install lizard

    - name: Refactor
      if: ${{ steps.changes.outputs.FILES_CHANGED != null }}
      run: |
        clang-format -i -style=file:.clang-format ${{ steps.changes.outputs.FILES_CHANGED }}
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git add .
        (git commit -m "Refactor by Github Actions" && git push origin HEAD:${{ env.TARGET_BRANCH }}) || expr 1 > /dev/null

    - name: Analyze with lizard
      if: ${{ steps.changes.outputs.FILES_CHANGED != null }}
      run: |
        echo "::add-matcher::.github/lizard.json"
        lizard -l cpp -w ${{ steps.changes.outputs.FILE_CHANGED }}

  build:
    needs: refactor_and_analyze
    strategy:
      matrix:
        arch: [x86, x64]
        variants: [debug, release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: ${{ matrix.arch }}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake --preset ${{ matrix.arch }}-${{ matrix.variants }}
        cmake --build out/build/${{ matrix.arch }}-${{ matrix.variants }}
        cmake --install out/build/${{ matrix.arch }}-${{ matrix.variants }}
