name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        preset: [x86-release, x64-release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmake --preset ${{ matrix.preset }}
        cmake --build out/build/${{ matrix.preset }}
        cmake --install out/build/${{ matrix.preset }}
