name: Release from tag

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      if: ${{ github.ref_name == 'main' }}
      with:
        ref: ${{ github.ref_name }}

    - name: Get versions
      id: versions
      if: ${{ github.ref_name == 'main' }}
      run: |
        echo "MAJOR_VERSION=`echo ${{ github.ref_name }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\1/"`" >> $GITHUB_OUTPUT
        echo "MINOR_VERSION=`echo ${{ github.ref_name }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\2/"`" >> $GITHUB_OUTPUT
        echo "PATCH_VERSION=`echo ${{ github.ref_name }} | sed -r "s/v([0-9]+)\.([0-9]+)\.([0-9]+).*/\3/"`" >> $GITHUB_OUTPUT

    - name: Set versions
      if: ${{ github.ref_name == 'main' }}
      run: |
        sed -i -zr "s/set\(VERSION_MAJOR [0-9]*\)/set(VERSION_MAJOR ${{ steps.versions.outputs.MAJOR }})/" CMakeLists.txt
        sed -i -zr "s/set\(VERSION_MINOR [0-9]*\)/set(VERSION_MINOR ${{ steps.versions.outputs.MINOR }})/" CMakeLists.txt
        sed -i -zr "s/set\(VERSION_PATCH [0-9]*\)/set(VERSION_PATCH ${{ steps.versions.outputs.PATCH }})/" CMakeLists.txt

    - name: Commit updates
      if: ${{ github.ref_name == 'main' }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git add .
        git commit -m "Update Versions by Github Actions"
        git push origin ${{ github.ref_name }}
